name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          rsync -av --exclude=' .git' --exclude='actions-runner' ./ /home/devops/my-api/ /home/devops/my-api/venv/bin/pip install -r /home/devops/my-api/requirements.txt
          sudo systemctl restart my-api
      
      - name: Health Check
        run: |
          sleep 2
          sudo systemctl is-active my-api
          curl --fail http://127.0.0.1:8000/health
